#!/bin/bash

brew update
brew install bash python3 neovim/neovim/neovim


bash ./lib/applications.bash
bash ./lib/settings.bash
bash ./lib/link.bash


# Manually
#     Install XCode
#     Transfer SSH key
#     Transfer WiFi keychain
#     Import terminal preferences from config/terminal/custom.terminal
#     Sign into chrome
#     Install Adobe CS6: https://helpx.adobe.com/x-productkb/policy-pricing/cs6-product-downloads.html
