#!/bin/bash

set -x

brew update
brew install bash python3 neovim/neovim/neovim npm rust


npm install -g svgo yo


pip3 install mercurial


bash ./lib/applications.bash
bash ./lib/settings.bash
bash ./lib/link.bash

# Install apps
#     android-file-transfer
#     appcleaner
#     flycut
#     google-chrome
#     macvim
#     plain-clip
#     reaper
#     sketch
#     skyfonts
#     slack
#     spectacle
#     thunderbird
#     transmission

# Add itunes music source to Spotify

# Manually before
#     Install homebrew
#         /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
#     Install XCode
#     Transfer SSH key

# Manually after
#     Transfer WiFi networks
#         security dump-keychain -d /Library/Keychains/System.keychain > output.txt
#         Open "System Preferences > Network > Advanced" and add all the networks manually
#     Transfer Thunderbird profile from ~/Library/Thunderbird/Profiles
#     Import terminal preferences from config/terminal/custom.terminal
#     Sign into chrome
