#!/bin/bash

function workon() { source ~/.virtualenvs/$1/bin/activate ;}

function _workon()
{
	local cur prev opts
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	opts="$(ls -d ~/.virtualenvs/*/ | tr '\n' '\0' | xargs -0 -n 1 basename)"
	COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
	return 0
}

complete -F _workon workon
