#!/bin/bash

rsync -vurlt --progress --delete "/Volumes/HardDrive/" "/Volumes/JonDwaiterBackup/" --exclude ".fseventsd" --exclude ".DS_Store" --exclude ".Spotlight-V100" --exclude ".Trashes" --exclude ".DocumentRevisions-V100" --exclude ".TemporaryItems"
