#!/bin/bash

rsync -vurlt --progress --delete "/Users/admin/Data/" "/Volumes/JonDwaiterBackup/" --exclude ".fseventsd" --exclude ".DS_Store" --exclude ".Spotlight-V100" --exclude ".Trashes" --exclude ".DocumentRevisions-V100" --exclude ".TemporaryItems" --exclude "/test"
