#!/bin/bash

URL=$(npm view "$1" dist.tarball)
DIR_NAME=$(echo "$1" | sed 's/\//_/g')

if [ $? -eq 0 ]; then
    curl -s "$URL" | tar xz
    mv package "$DIR_NAME"
    printf "# Source\n\n$URL\n" > ./"$DIR_NAME"/SOURCE.md
    printf "$URL\n"
fi
