#!/usr/bin/env python

import re
import sys

def main():
    level = int(sys.argv[1])
    format_link = sys.argv[2]
    heading_character = '#'
    heading_prefix = heading_character * level
    heading_regex = '^' + heading_prefix + '([^#].*)'

    for line in sys.stdin:
        match = re.match(heading_regex, line)
        if match != None:
            title = match.group(1).strip()
            slug = slugify(title)

            formatted = format_link.format(title=title, slug=slug)
            sys.stdout.write(formatted + '\n')

def slugify(s):
    s = s.strip().lower()
    s = re.sub('[^\w ]', '', s)
    return re.sub(' +', '-', s)

main()
