#!/usr/bin/env python

import os
import sys
import subprocess

sys.path.insert(1, os.getcwd())

import fabfile
from fabfile import env

fabfile.dev()

commands = [
    "cd {}".format(env.site_path),
    "source {}/bin/activate".format(env.venv_path),
]

commands_str = ";".join(commands)

subprocess.call(["vagrant", "ssh", "--", "-t",
    "sudo bash -c \"bash --init-file <(echo '{}')\"".format(commands_str)])
