if has("neovim")
    runtime! plugin/python_setup.vim
endif

" Load plugins
set runtimepath^=$HOME/.vim/bundle/colors_solarized
set runtimepath^=$HOME/.vim/bundle/commentary
set runtimepath^=$HOME/.vim/bundle/ctrlp
set runtimepath^=$HOME/.vim/bundle/easy_motion
set runtimepath^=$HOME/.vim/bundle/emmet
set runtimepath^=$HOME/.vim/bundle/exchange
set runtimepath^=$HOME/.vim/bundle/gnupg
set runtimepath^=$HOME/.vim/bundle/indent_object
set runtimepath^=$HOME/.vim/bundle/line_object
set runtimepath^=$HOME/.vim/bundle/my_completions
set runtimepath^=$HOME/.vim/bundle/my_disabled_indents
set runtimepath^=$HOME/.vim/bundle/neovim_clipboard
set runtimepath^=$HOME/.vim/bundle/nerdtree
set runtimepath^=$HOME/.vim/bundle/puppet_syntax
set runtimepath^=$HOME/.vim/bundle/repeat
set runtimepath^=$HOME/.vim/bundle/rust
set runtimepath^=$HOME/.vim/bundle/surround
set runtimepath^=$HOME/.vim/bundle/sneak
set runtimepath^=$HOME/.vim/bundle/taboo
set runtimepath^=$HOME/.vim/bundle/titlecase
set runtimepath^=$HOME/.vim/bundle/user_object " Required by line_object

if has("gui_running")
    " Doesn't work with neovim yet
    set runtimepath^=$HOME/.vim/bundle/ultisnips
endif

if has("neovim")
    source ~/.vimrc.d/neovim.vim
endif

source ~/.vimrc.d/setting.vim
source ~/.vimrc.d/plugin.vim
source ~/.vimrc.d/keymap.vim
source ~/.vimrc.d/command.vim
source ~/.vimrc.d/autocmd.vim
source ~/.vimrc.d/function.vim
source ~/.vimrc.d/color.vim
