" Pathogen
runtime bundle/pathogen/autoload/pathogen.vim
execute pathogen#infect()


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" General
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

set nocompatible                  " Get rid of Vi compatibility mode
filetype plugin on
filetype indent on

set number                        " Show line numbers
set linebreak                     " Break lines at word (requires Wrap lines)
set visualbell                    " Use visual bell (no beeping)

set nohlsearch                    " Don't highlight search results
set noshowmatch                   " Don't highlight matching bracket
set smartcase                     " Ignore case unless uppercase
set ignorecase                    " Always case-insensitive
set incsearch                     " Searches for strings incrementally

set autoindent                    " Auto-indent new lines
set expandtab                     " Use spaces instead of tabs
set shiftwidth=4                  " Number of auto-indent spaces
set smartindent                   " Enable smart-indent
set smarttab                      " Enable smart-tabs
set tabstop=4                     " Displayed width of tabs
set softtabstop=4                 " Number of spaces per Tab

syntax on                         " Syntax highlighting
set t_Co=256                      " Enable 256-color mode
colorscheme solarized

set foldmethod=indent             " Fold based on indent
set nofoldenable                  " Don't fold by default
set foldnestmax=4                 " Deepest fold is 4 levels
set foldlevel=4                   " Don't close all folds the first time

" set noesckeys                     " Make Escape key respond immediately

set ruler                         " Show row and column ruler information
set undolevels=1000               " Number of undo levels

set encoding=utf-8
set lazyredraw                    " Don't update display while executing macros
set autoread                      " Auto update if file has changed outside Vim
set showcmd                       " Show current command on status line
set wildmenu
set backspace=indent,start        " Backspace over indent and insert start
set laststatus=2                  " Always show status bar


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Plugin
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

let g:ctrlp_map = ''
let g:ctrlp_working_path_mode = ''
let g:ctrlp_custom_ignore = {
    \ 'file': '\v\.(pyc|aux|bbl|blg|fdb_latexmk|lof|log|lot|toc|out|synctex\.gz)$',
    \ }

let g:loaded_matchparen = 1       " Don't highlight matching brackets

" Disable automatic comment insertion
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

runtime macros/matchit.vim        " Use matchit included with Vim


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Keymaps
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

let mapleader = ","

nnoremap Y y$

" Use Ctrl-[hjkl] to select the active split
nnoremap <silent> <C-K> :wincmd k<CR>
nnoremap <silent> <C-J> :wincmd j<CR>
nnoremap <silent> <C-H> :wincmd h<CR>
nnoremap <silent> <C-L> :wincmd l<CR>

" Mac terminal interprets C-Space as C-@
inoremap <C-Space> <C-X><C-O>
inoremap <C-@> <C-X><C-O>

" CtrlP
nnoremap <silent> <leader>f :CtrlP<CR>
nnoremap <silent> <leader>b :CtrlPBuffer<CR>

" Ctrl-s for save
nnoremap <silent> <leader>w :write<CR>

" Folding only on the nth evel
nnoremap <silent> <leader>z1 :setlocal foldnestmax=1<CR>:setlocal foldlevel=0<CR>:setlocal foldenable<CR>
nnoremap <silent> <leader>z2 :setlocal foldnestmax=2<CR>:setlocal foldlevel=1<CR>:setlocal foldenable<CR>
nnoremap <silent> <leader>z3 :setlocal foldnestmax=3<CR>:setlocal foldlevel=2<CR>:setlocal foldenable<CR>
nnoremap <silent> <leader>z4 :setlocal foldnestmax=4<CR>:setlocal foldlevel=3<CR>:setlocal foldenable<CR>

nnoremap <silent> <leader>d yyPj
vnoremap <silent> <leader>d yP`<

nnoremap <silent> <leader>c :bp<bar>bd #<CR>
