" General

set number                        " Show line numbers
set linebreak                     " Break lines at word (requires Wrap lines)
set showbreak=+++                 " Wrap-broken line prefix
set textwidth=100                 " Line wrap (number of cols)
set visualbell                    " Use visual bell (no beeping)

set nohlsearch                    " Don't highlight search results
set noshowmatch                   " Don't highlight matching bracket
set smartcase                     " Enable smart-case search
set ignorecase                    " Always case-insensitive
set incsearch                     " Searches for strings incrementally

set autoindent                    " Auto-indent new lines
set expandtab                     " Use spaces instead of tabs
set shiftwidth=4                  " Number of auto-indent spaces
set smartindent                   " Enable smart-indent
set smarttab                      " Enable smart-tabs
set softtabstop=4                 " Number of spaces per Tab

syntax on                         " Syntax highlighting

set foldmethod=indent             " Fold based on indent
set nofoldenable                  " Don't fold by default
set foldnestmax=4                 " Deepest fold is 4 levels


" Advanced

set ruler                         " Show row and column ruler information

set undolevels=1000               " Number of undo levels
set backspace=indent,eol,start    " Backspace behaviour


" Plugins

let g:ctrlp_map = '<c-p>'
let g:loaded_matchparen = 1       " Don't highlight matching brackets


" Keymaps
