#!/bin/bash

rsync -vurlt --progress --delete "/Volumes/Hard Drive/" "/Volumes/Jon Dwaiter Backup/" --exclude ".fseventsd" --exclude ".DS_Store" --exclude ".Spotlight-V100" --exclude ".Trashes" --exclude ".DocumentRevisions-V100"
